import serial
import serial.tools.list_ports

class GPos:
    def __init__(self, pos: float, speed: float):
        self.p = pos
        self.s = speed

        self.r()

    def pos(self):
        return self.p

    def speed(self):
        return self.s

    def r(self):
        return self.p, self.s

class GWriteError:
    def __init__(self):
        pass

    def displayError(self, error: str):
        print(f'GWriteError: {error}')

class GWriteExtruder:
    def __init__(self):
        self.temp = 0

    def setTemp(self, temp: int):
        if temp >= 0:
            self.temp = temp
            return f'M104 S{self.temp} ; Set extruder temp'
        else:
            GWriteError.displayError(GWriteError, 'extruder temperature cannot be negative.')
            return ''

    def extrude(self, amount: float, speed: float):
        if self.temp >= 190:
            return f'G1 E{amount} F{speed} ; Extrude filament'
        else:
            GWriteError.displayError(GWriteError, 'extruder temperature not set, extrusion disabled.')
            return ''

class GWriteHeatbed:
    def __init__(self):
        self.temp = 0

    def setTemp(self, temp: int):
        if temp >= 0:
            self.temp = temp
            return f'M140 S{self.temp} ; Set heatbed temp'
        else:
            GWriteError.displayError(GWriteError, 'heatbed temperature cannot be negative.')
            return ''

class GWriteFilament:
    def __init__(self, extruderTemp: int, heatbedTemp: int):
        if extruderTemp >= 190:
            self.e = extruderTemp
        else:
            GWriteError.displayError(GWriteError, 'extruder temp cannot be less than 190 degrees celsius.')
            self.e = 0
        if heatbedTemp >= 50:
            self.h = heatbedTemp
        else:
            GWriteError.displayError(GWriteError, 'heatbed temp cannot be less than 190 degrees celsius.')
            self.h = 0

    def extruderTemp(self):
        return self.e

    def heatbedTemp(self):
        return self.h

class GWritePrinter:
    XAxis = 'x'
    YAxis = 'y'
    ZAxis = 'z'

    def __init__(self):
        self.extruder = GWriteExtruder()
        self.heatbed = GWriteHeatbed()
        self.commands: list[str] = []
        self.commands.append('; Generated by GWrite')
        self.commands.append('; Copyright (C) GWrite 2024\n\n')

    def homeAxis(self, axis):
        if axis == 'x':
            self.commands.append(f'G28 X ; Home x axis')
        elif axis == 'y':
            self.commands.append(f'G28 Y ; Home y axis')
        else:
            self.commands.append(f'G28 Z ; Home z axis')

    def homePrinter(self):
        self.commands.append('G28 ; Home all axis')

    def levelBed(self):
        self.commands.append('G29 ; Mesh bed leveling')

    def setAbsoluteMode(self):
        self.commands.append('G90 ; Set coordinates interpreted as absolute')

    def setRelativeMode(self):
        self.commands.append('G91 ; Set coordinates interpreted as relative')

    def setX(self, pos: GPos):
        self.commands.append(f'G1 X{pos.pos()} F{pos.speed()} ; Move x axis')

    def setY(self, pos: GPos):
        self.commands.append(f'G1 Y{pos.pos()} F{pos.speed()} ; Move y axis')

    def setZ(self, pos: GPos):
        self.commands.append(f'G1 Z{pos.pos()} F{pos.speed()} ; Move z axis')

    def heatExtruderToTemp(self, temp: int):
        self.commands.append(self.extruder.setTemp(temp))

    def heatBedToTemp(self, temp: int):
        self.commands.append(self.heatbed.setTemp(temp))

    def prepareFor(self, filament: GWriteFilament):
        self.heatExtruderToTemp(filament.extruderTemp())
        self.heatBedToTemp(filament.heatbedTemp())

    def extrude(self, amount: GPos):
        self.commands.append(self.extruder.extrude(amount.pos(), amount.speed()))

    def addCustomCommand(self, command: str):
        self.commands.append(command)

    def addComment(self, comment: str):
        self.commands.append(f'\n; {comment}\n')

    def generate(self, filename: str):
        with open(filename, 'w') as f:
            for c in self.commands:
                f.write(f'{c}\n')

            f.write(f'\n; {len(self.commands)} total lines of GCODE generated')

    def sendCodeToPrinter(self, baudrate: int = 115200):
        ports = serial.tools.list_ports.comports()
        if not ports:
            print('No serial ports found.')
            return

        port = ports[0].device
        try:
            with serial.Serial(port, baudrate, timeout=2) as ser:
                for command in self.commands:
                    ser.write(f'{command}\n'.encode())
                    response = ser.readline().decode().strip()
                    print(f'Printer response: {response}')
        except serial.SerialException as e:
            GWriteError.displayError(GWriteError, f'failed to connect to printer \n{e}')
