

class GPos:
    def __init__(self, pos: float, speed: float):
        self.p = pos
        self.s = speed

        self.r()

    def pos(self):
        return self.p

    def speed(self):
        return self.s

    def r(self):
        return self.p, self.s

class GWriteError:
    def __init__(self):
        pass

    def displayError(self, error: str):
        print(f'GWriteError: {error}')

class GWriteExtruder:
    def __init__(self):
        self.temp = 0

    def setTemp(self, temp: int):
        if temp >= 0:
            self.temp = temp
            return f'M104 S{self.temp}'
        else:
            GWriteError.displayError(GWriteError, 'extruder temperature cannot be negative.')
            return ''

    def extrude(self, amount: float, speed: float):
        if self.temp > 190:
            return f'G1 E{amount} F{speed}'
        else:
            GWriteError.displayError(GWriteError, 'extruder temperature not set, extrusion disabled.')
            return ''

class GWriteHeatbed:
    def __init__(self):
        self.temp = 0

    def setTemp(self, temp: int):
        if temp >= 0:
            self.temp = temp
            return f'M104 S{self.temp}'
        else:
            GWriteError.displayError(GWriteError, 'heatbed temperature cannot be negative.')
            return ''

class GWritePrinter:
    XAxis = 'x'
    YAxis = 'y'
    ZAxis = 'z'

    def __init__(self):
        self.extruder = GWriteExtruder()
        self.heatbed = GWriteHeatbed()
        self.commands: list[str] = []
        self.commands.append('; Generated by GWrite')
        self.commands.append('; Copyright (C) GWrite 2024')

    def homeAxis(self, axis):
        if axis == 'x':
            self.commands.append(f'G28 X ; Home x axis')
        elif axis == 'y':
            self.commands.append(f'G28 Y ; Home y axis')
        else:
            self.commands.append(f'G28 Z ; Home z axis')

    def homePrinter(self):
        self.commands.append('G28 ; Home all axis')

    def levelBed(self):
        self.commands.append('G29 ; Mesh bed leveling')

    def setAbsoluteMode(self):
        self.commands.append('G90 ; Set coordinates interpreted as absolute')

    def setRelativeMode(self):
        self.commands.append('G91 ; Set coordinates interpreted as relative')

    def setX(self, pos: GPos):
        self.commands.append(f'G1 X{pos.pos()} F{pos.speed()}')

    def setY(self, pos: GPos):
        self.commands.append(f'G1 Y{pos.pos()} F{pos.speed()}')

    def setZ(self, pos: GPos):
        self.commands.append(f'G1 Z{pos.pos()} F{pos.speed()}')

    def heatExtruderToTemp(self, temp: int):
        self.commands.append(self.extruder.setTemp(temp))

    def extrude(self, amount: GPos):
        self.commands.append(self.extruder.extrude(amount.pos(), amount.speed()))

    def addCustomCommand(self, command: str):
        self.commands.append(command)

    def generate(self, filename: str):
        with open(filename, 'w') as f:
            for c in self.commands:
                f.write(f'{c}\n')
