; Generated by GWrite
; Copyright (C) GWrite 2024


G28 ; Home all axis
G29 ; Mesh bed leveling
M104 S200 ; Set extruder temp
M140 S60 ; Set heatbed temp
G1 E100 F1000 ; Extrude filament
G1 Z100 F1000 ; Move z axis

; This is a test file.


; 9 total lines of GCODE generated